name: Build/Push Management Center latest image

on:
  push:
    branches: enhancement/multi-arch-builds

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: v0.4.1
          qemu-version: 4.2.0-7

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build/Push Management Center image
        run: |
          docker buildx build --push \
            --tag hasancelik/management-center:latest \
            --platform=linux/arm64,linux/amd64,linux/ppc64le,linux/s390x .